name: Build and test
on:
  repository_dispatch:
    types: [artifact_ready]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dependent_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: make library
        run: make
        working-directory: src
      - name: Download artifact from poivre
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.client_payload.artifact_name }}
          repository: pauldardeau/poivre
          run-id: $${{ github.event.client_payload.run_id }}
          token: $${{ secrets.REPO_POIVRE_PAT }}
      - name: make-tests using artifact from poivre
        run: make
        working-directory: tests
      - name: run-tests
        run: ./test_chaudiere
        working-directory: tests
